spring:
  profiles:
    active: dev
---
server:
  port: 8001
spring:
  profiles: dev  #开发环境
  application:
    name: USER-PROVIDER
eureka:
  client:
    fetch-registry: false #是否注册到eureka
    register-with-eureka: false #是否从服务获取注册信息
    service-url:   
      defaultZone: http://eureka-7001.com:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip
---
server:
  port: 8847
spring:
  profiles: test  #测试环境
  application:
    name: USER-PROVIDER-TEST
eureka:
  client:
    fetch-registry: false #是否注册到eureka
    register-with-eureka: false #是否从服务获取注册信息
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip